project: esim-myanmar

name: esim-myanmar-workers
main: build/index.html
compatibility_date: "2024-01-01"

[site]
bucket = "./build"

[[routes]]
pattern = "/*"
zone_name = "esim.com.mm"

[env.production]
name = "esim-myanmar-prod"

[env.staging]
name = "esim-myanmar-staging"
